### ISSUE TITLE
Redownloading Resets the Date on Older Notes

### ISSUE THREAD

**Issue by reformationacres** [smartsteader/beta#17]
![img_6310 2](https://user-images.githubusercontent.com/24949169/30979548-f3164c4e-a44b-11e7-8b15-bf17cf3c64a3.PNG)
![img_6309](https://user-images.githubusercontent.com/24949169/30979686-5ffa6c46-a44c-11e7-8279-d8e19871dc3e.PNG)

**Comment by neilmcguire** [comment]
Looked at the data for this particular note and found that the correct date was present in the database but did not have the correct field name. Should show up correctly now.

**Comment by neilmcguire** [comment]
@reformationacres Let me know if this is still an issue.
