### ISSUE TITLE
Custom Expense Category 

### ISSUE THREAD

**Issue by reformationacres** [smartsteader/beta#24]
Based on a new user suggestion: So that we don't have to create new categories for each possible area of production out there (quail, alpacas, general farm infrastructure, LGD's, etc...) could we create a basic name (or create) your own category of expenses?

**Comment by neilmcguire** [comment]
We could create a 'Custom Production Record' with the Barn as the image, and then it would show up as whatever name they had with subtitle 'Custom Production Record'. Would that accomplish what we are looking for?

**Comment by reformationacres** [comment]
Sounds great!

**Comment by neilmcguire** [comment]
Added in version 0.3.2 for both android and iOS.
